<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block newsletter container">
    <div class="row">
        <div class="col-md-5">
            <div class="newsletter-desc ">
                <?php /* @escapeNotVerified */
                echo __('Subscribe to the CleanJinn mailing list to receive updates on new arrivals, special offers and other discount information.') ?>
            </div>
        </div>
        <div class="content  col-md-7">
            <form class="form subscribe"
                  novalidate
                  action="<?php /* @escapeNotVerified */
                  echo $block->getFormActionUrl() ?>"
                  method="post"
                  data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                  id="newsletter-validate-detail">
                <div class="field newsletter">
                    <div class="control">
                        <input name="email" type="email" id="newsletter"
                               placeholder="<?php /* @escapeNotVerified */
                               echo __('Enter your email address') ?>"
                               data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                </div>
                <div class="actions">
                    <button class="action subscribe primary" title="<?php /* @escapeNotVerified */
                    echo __('Subscribe') ?>" type="submit">
                        <span><?php /* @escapeNotVerified */
                            echo __('Subscribe') ?></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
