<?php
/**
 *
 * Copyright © 2015 TemplateMonster. All rights reserved.
 * See COPYING.txt for license details.
 *
 */

?>
<script type="text/x-magento-init">
{
    "#widget_instace_tabs_properties_section_content": {
		"featuredProductWidget": {},
		"featuredProductWidgetTabs": {
		    "widgetInstance": "featured_products",
		    "tabSections": {
		        "General": ["product_types", "product_ids", "categories", "css_class", "cache_lifetime"],
		        "View":    ["product_image_width", "product_image_height", "product_name_length", "show_carousel",
		                    "number_per_view", "number_to_display", "number_per_row", "use_arrows", "prev_button",
		                    "next_button", "use_pagination"],
		        "Labels":  ["show_label"],
		        "Banner":  ["is_banner", "banner_content"],
		        "Gallery": ["hover_type", "carousel_slides_count", "gallery_slides_count", "thumb_width", "thumb_height"]
		    }
		}
    }
}
</script>